package metier;
// Generated 27 mars 2019 10:56:33 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Contenires generated by hbm2java
 */
public class Contenires  implements java.io.Serializable {


     private ConteniresId id;
     private Exercicestandard exercicestandard;
     private Ordre ordre;
     private Seancestandard seancestandard;
     private Integer nbseries;
     private Integer tempsreposs;

    public Contenires() {
    }

	
    public Contenires(ConteniresId id, Exercicestandard exercicestandard, Ordre ordre, Seancestandard seancestandard) {
        this.id = id;
        this.exercicestandard = exercicestandard;
        this.ordre = ordre;
        this.seancestandard = seancestandard;
    }
    public Contenires(ConteniresId id, Exercicestandard exercicestandard, Ordre ordre, Seancestandard seancestandard, Integer nbseries, Integer tempsreposs) {
       this.id = id;
       this.exercicestandard = exercicestandard;
       this.ordre = ordre;
       this.seancestandard = seancestandard;
       this.nbseries = nbseries;
       this.tempsreposs = tempsreposs;
    }
   
    public ConteniresId getId() {
        return this.id;
    }
    
    public void setId(ConteniresId id) {
        this.id = id;
    }
    public Exercicestandard getExercicestandard() {
        return this.exercicestandard;
    }
    
    public void setExercicestandard(Exercicestandard exercicestandard) {
        this.exercicestandard = exercicestandard;
    }
    public Ordre getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(Ordre ordre) {
        this.ordre = ordre;
    }
    public Seancestandard getSeancestandard() {
        return this.seancestandard;
    }
    
    public void setSeancestandard(Seancestandard seancestandard) {
        this.seancestandard = seancestandard;
    }
    public Integer getNbseries() {
        return this.nbseries;
    }
    
    public void setNbseries(Integer nbseries) {
        this.nbseries = nbseries;
    }
    public Integer getTempsreposs() {
        return this.tempsreposs;
    }
    
    public void setTempsreposs(Integer tempsreposs) {
        this.tempsreposs = tempsreposs;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 71 * hash + Objects.hashCode(this.id);
        hash = 71 * hash + Objects.hashCode(this.ordre);
        hash = 71 * hash + Objects.hashCode(this.nbseries);
        hash = 71 * hash + Objects.hashCode(this.tempsreposs);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Contenires other = (Contenires) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.ordre, other.ordre)) {
            return false;
        }
        if (!Objects.equals(this.nbseries, other.nbseries)) {
            return false;
        }
        if (!Objects.equals(this.tempsreposs, other.tempsreposs)) {
            return false;
        }
        return true;
    }




}


