package metier;
// Generated 27 mars 2019 12:04:47 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Contenirss generated by hbm2java
 */
public class Contenirss  implements java.io.Serializable {


     private ContenirssId id;
     private Ordre ordre;
     private Programmestandard programmestandard;
     private Seancestandard seancestandard;
     private Semainess semainess;

    public Contenirss() {
    }

    public Contenirss(ContenirssId id, Ordre ordre, Programmestandard programmestandard, Seancestandard seancestandard, Semainess semainess) {
       this.id = id;
       this.ordre = ordre;
       this.programmestandard = programmestandard;
       this.seancestandard = seancestandard;
       this.semainess = semainess;
    }
   
    public ContenirssId getId() {
        return this.id;
    }
    
    public void setId(ContenirssId id) {
        this.id = id;
    }
    public Ordre getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(Ordre ordre) {
        this.ordre = ordre;
    }
    public Programmestandard getProgrammestandard() {
        return this.programmestandard;
    }
    
    public void setProgrammestandard(Programmestandard programmestandard) {
        this.programmestandard = programmestandard;
    }
    public Seancestandard getSeancestandard() {
        return this.seancestandard;
    }
    
    public void setSeancestandard(Seancestandard seancestandard) {
        this.seancestandard = seancestandard;
    }
    public Semainess getSemainess() {
        return this.semainess;
    }
    
    public void setSemainess(Semainess semainess) {
        this.semainess = semainess;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 37 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Contenirss other = (Contenirss) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }




}


