package metier;
// Generated 27 mars 2019 12:04:47 by Hibernate Tools 4.3.1



/**
 * ConteniresId generated by hbm2java
 */
public class ConteniresId  implements java.io.Serializable {


     private int codess;
     private int codees;
     private int numero;

    public ConteniresId() {
    }

    public ConteniresId(int codess, int codees, int numero) {
       this.codess = codess;
       this.codees = codees;
       this.numero = numero;
    }
   
    public int getCodess() {
        return this.codess;
    }
    
    public void setCodess(int codess) {
        this.codess = codess;
    }
    public int getCodees() {
        return this.codees;
    }
    
    public void setCodees(int codees) {
        this.codees = codees;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConteniresId) ) return false;
		 ConteniresId castOther = ( ConteniresId ) other; 
         
		 return (this.getCodess()==castOther.getCodess())
 && (this.getCodees()==castOther.getCodees())
 && (this.getNumero()==castOther.getNumero());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodess();
         result = 37 * result + this.getCodees();
         result = 37 * result + this.getNumero();
         return result;
   }   


}


