package metier;
// Generated 27 mars 2019 10:56:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Employe generated by hbm2java
 */
public class Employe  implements java.io.Serializable {


     private Integer codeem;
     private String nomem;
     private String prenomem;
     private String telem;
     private String adremailem;
     private String motdepasseem;
     private String typeem;
     private Set programmepersos = new HashSet(0);
     private Set programmestandards = new HashSet(0);

    public Employe() {
    }

    public Employe(String nomem, String prenomem, String telem, String adremailem, String motdepasseem, String typeem, Set programmepersos, Set programmestandards) {
       this.nomem = nomem;
       this.prenomem = prenomem;
       this.telem = telem;
       this.adremailem = adremailem;
       this.motdepasseem = motdepasseem;
       this.typeem = typeem;
       this.programmepersos = programmepersos;
       this.programmestandards = programmestandards;
    }
   
    public Integer getCodeem() {
        return this.codeem;
    }
    
    public void setCodeem(Integer codeem) {
        this.codeem = codeem;
    }
    public String getNomem() {
        return this.nomem;
    }
    
    public void setNomem(String nomem) {
        this.nomem = nomem;
    }
    public String getPrenomem() {
        return this.prenomem;
    }
    
    public void setPrenomem(String prenomem) {
        this.prenomem = prenomem;
    }
    public String getTelem() {
        return this.telem;
    }
    
    public void setTelem(String telem) {
        this.telem = telem;
    }
    public String getAdremailem() {
        return this.adremailem;
    }
    
    public void setAdremailem(String adremailem) {
        this.adremailem = adremailem;
    }
    public String getMotdepasseem() {
        return this.motdepasseem;
    }
    
    public void setMotdepasseem(String motdepasseem) {
        this.motdepasseem = motdepasseem;
    }
    public String getTypeem() {
        return this.typeem;
    }
    
    public void setTypeem(String typeem) {
        this.typeem = typeem;
    }
    public Set getProgrammepersos() {
        return this.programmepersos;
    }
    
    public void setProgrammepersos(Set programmepersos) {
        this.programmepersos = programmepersos;
    }
    public Set getProgrammestandards() {
        return this.programmestandards;
    }
    
    public void setProgrammestandards(Set programmestandards) {
        this.programmestandards = programmestandards;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.codeem);
        hash = 79 * hash + Objects.hashCode(this.nomem);
        hash = 79 * hash + Objects.hashCode(this.prenomem);
        hash = 79 * hash + Objects.hashCode(this.telem);
        hash = 79 * hash + Objects.hashCode(this.adremailem);
        hash = 79 * hash + Objects.hashCode(this.motdepasseem);
        hash = 79 * hash + Objects.hashCode(this.typeem);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Employe other = (Employe) obj;
        if (!Objects.equals(this.nomem, other.nomem)) {
            return false;
        }
        if (!Objects.equals(this.prenomem, other.prenomem)) {
            return false;
        }
        if (!Objects.equals(this.telem, other.telem)) {
            return false;
        }
        if (!Objects.equals(this.adremailem, other.adremailem)) {
            return false;
        }
        if (!Objects.equals(this.motdepasseem, other.motdepasseem)) {
            return false;
        }
        if (!Objects.equals(this.typeem, other.typeem)) {
            return false;
        }
        if (!Objects.equals(this.codeem, other.codeem)) {
            return false;
        }
        return true;
    }




}


