package metier;
// Generated 27 mars 2019 10:56:33 by Hibernate Tools 4.3.1


import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Exercicestandard generated by hbm2java
 */
public class Exercicestandard  implements java.io.Serializable {


     private Integer codees;
     private String nomes;
     private byte[] descriptionmediaes;
     private String descriptiontxtes;
     private Integer tempsobjectifes;
     private Set contenireses = new HashSet(0);
     private Set objectifes = new HashSet(0);
     private Set repetitions = new HashSet(0);

    public Exercicestandard() {
    }

    public Exercicestandard(String nomes, byte[] descriptionmediaes, String descriptiontxtes, Integer tempsobjectifes, Set contenireses, Set objectifes, Set repetitions) {
       this.nomes = nomes;
       this.descriptionmediaes = descriptionmediaes;
       this.descriptiontxtes = descriptiontxtes;
       this.tempsobjectifes = tempsobjectifes;
       this.contenireses = contenireses;
       this.objectifes = objectifes;
       this.repetitions = repetitions;
    }
   
    public Integer getCodees() {
        return this.codees;
    }
    
    public void setCodees(Integer codees) {
        this.codees = codees;
    }
    public String getNomes() {
        return this.nomes;
    }
    
    public void setNomes(String nomes) {
        this.nomes = nomes;
    }
    public byte[] getDescriptionmediaes() {
        return this.descriptionmediaes;
    }
    
    public void setDescriptionmediaes(byte[] descriptionmediaes) {
        this.descriptionmediaes = descriptionmediaes;
    }
    public String getDescriptiontxtes() {
        return this.descriptiontxtes;
    }
    
    public void setDescriptiontxtes(String descriptiontxtes) {
        this.descriptiontxtes = descriptiontxtes;
    }
    public Integer getTempsobjectifes() {
        return this.tempsobjectifes;
    }
    
    public void setTempsobjectifes(Integer tempsobjectifes) {
        this.tempsobjectifes = tempsobjectifes;
    }
    public Set getContenireses() {
        return this.contenireses;
    }
    
    public void setContenireses(Set contenireses) {
        this.contenireses = contenireses;
    }
    public Set getObjectifes() {
        return this.objectifes;
    }
    
    public void setObjectifes(Set objectifes) {
        this.objectifes = objectifes;
    }
    public Set getRepetitions() {
        return this.repetitions;
    }
    
    public void setRepetitions(Set repetitions) {
        this.repetitions = repetitions;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 83 * hash + Objects.hashCode(this.codees);
        hash = 83 * hash + Objects.hashCode(this.nomes);
        hash = 83 * hash + Arrays.hashCode(this.descriptionmediaes);
        hash = 83 * hash + Objects.hashCode(this.descriptiontxtes);
        hash = 83 * hash + Objects.hashCode(this.tempsobjectifes);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Exercicestandard other = (Exercicestandard) obj;
        if (!Objects.equals(this.nomes, other.nomes)) {
            return false;
        }
        if (!Objects.equals(this.descriptiontxtes, other.descriptiontxtes)) {
            return false;
        }
        if (!Objects.equals(this.codees, other.codees)) {
            return false;
        }
        if (!Arrays.equals(this.descriptionmediaes, other.descriptionmediaes)) {
            return false;
        }
        if (!Objects.equals(this.tempsobjectifes, other.tempsobjectifes)) {
            return false;
        }
        return true;
    }




}


