package metier;
// Generated 27 mars 2019 10:56:33 by Hibernate Tools 4.3.1



/**
 * FaireexeId generated by hbm2java
 */
public class FaireexeId  implements java.io.Serializable {


     private int codec;
     private int codeep;

    public FaireexeId() {
    }

    public FaireexeId(int codec, int codeep) {
       this.codec = codec;
       this.codeep = codeep;
    }
   
    public int getCodec() {
        return this.codec;
    }
    
    public void setCodec(int codec) {
        this.codec = codec;
    }
    public int getCodeep() {
        return this.codeep;
    }
    
    public void setCodeep(int codeep) {
        this.codeep = codeep;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FaireexeId) ) return false;
		 FaireexeId castOther = ( FaireexeId ) other; 
         
		 return (this.getCodec()==castOther.getCodec())
 && (this.getCodeep()==castOther.getCodeep());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodec();
         result = 37 * result + this.getCodeep();
         return result;
   }   


}


