package metier;
// Generated 27 mars 2019 10:56:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ordre generated by hbm2java
 */
public class Ordre  implements java.io.Serializable {


     private int numero;
     private Set contenireses = new HashSet(0);
     private Set contenirsses = new HashSet(0);

    public Ordre() {
    }

	
    public Ordre(int numero) {
        this.numero = numero;
    }
    public Ordre(int numero, Set contenireses, Set contenirsses) {
       this.numero = numero;
       this.contenireses = contenireses;
       this.contenirsses = contenirsses;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Set getContenireses() {
        return this.contenireses;
    }
    
    public void setContenireses(Set contenireses) {
        this.contenireses = contenireses;
    }
    public Set getContenirsses() {
        return this.contenirsses;
    }
    
    public void setContenirsses(Set contenirsses) {
        this.contenirsses = contenirsses;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + this.numero;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Ordre other = (Ordre) obj;
        if (this.numero != other.numero) {
            return false;
        }
        return true;
    }




}


