package metier;
// Generated 27 mars 2019 12:04:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Profil generated by hbm2java
 */
public class Profil  implements java.io.Serializable {


     private Integer codepro;
     private String libellepro;
     private String agepro;
     private String poidspro;
     private String sexepro;
     private Set programmestandards = new HashSet(0);
     private Set clients = new HashSet(0);

    public Profil() {
    }

    public Profil(String libellepro, String agepro, String poidspro, String sexepro, Set programmestandards, Set clients) {
       this.libellepro = libellepro;
       this.agepro = agepro;
       this.poidspro = poidspro;
       this.sexepro = sexepro;
       this.programmestandards = programmestandards;
       this.clients = clients;
    }
   
    public Integer getCodepro() {
        return this.codepro;
    }
    
    public void setCodepro(Integer codepro) {
        this.codepro = codepro;
    }
    public String getLibellepro() {
        return this.libellepro;
    }
    
    public void setLibellepro(String libellepro) {
        this.libellepro = libellepro;
    }
    public String getAgepro() {
        return this.agepro;
    }
    
    public void setAgepro(String agepro) {
        this.agepro = agepro;
    }
    public String getPoidspro() {
        return this.poidspro;
    }
    
    public void setPoidspro(String poidspro) {
        this.poidspro = poidspro;
    }
    public String getSexepro() {
        return this.sexepro;
    }
    
    public void setSexepro(String sexepro) {
        this.sexepro = sexepro;
    }
    public Set getProgrammestandards() {
        return this.programmestandards;
    }
    
    public void setProgrammestandards(Set programmestandards) {
        this.programmestandards = programmestandards;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + Objects.hashCode(this.codepro);
        hash = 89 * hash + Objects.hashCode(this.libellepro);
        hash = 89 * hash + Objects.hashCode(this.agepro);
        hash = 89 * hash + Objects.hashCode(this.poidspro);
        hash = 89 * hash + Objects.hashCode(this.sexepro);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Profil other = (Profil) obj;
        if (!Objects.equals(this.libellepro, other.libellepro)) {
            return false;
        }
        if (!Objects.equals(this.agepro, other.agepro)) {
            return false;
        }
        if (!Objects.equals(this.poidspro, other.poidspro)) {
            return false;
        }
        if (!Objects.equals(this.sexepro, other.sexepro)) {
            return false;
        }
        if (!Objects.equals(this.codepro, other.codepro)) {
            return false;
        }
        return true;
    }




}


