package metier;
// Generated 27 mars 2019 12:04:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Programmestandard generated by hbm2java
 */
public class Programmestandard  implements java.io.Serializable {


     private Integer codeps;
     private Employe employe;
     private String nomps;
     private String descriptionps;
     private Integer nbsemaines;
     private Set contenirsses = new HashSet(0);
     private Set profils = new HashSet(0);

    public Programmestandard() {
    }

	
    public Programmestandard(Employe employe) {
        this.employe = employe;
    }
    public Programmestandard(Employe employe, String nomps, String descriptionps, Integer nbsemaines, Set contenirsses, Set profils) {
       this.employe = employe;
       this.nomps = nomps;
       this.descriptionps = descriptionps;
       this.nbsemaines = nbsemaines;
       this.contenirsses = contenirsses;
       this.profils = profils;
    }
   
    public Integer getCodeps() {
        return this.codeps;
    }
    
    public void setCodeps(Integer codeps) {
        this.codeps = codeps;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public String getNomps() {
        return this.nomps;
    }
    
    public void setNomps(String nomps) {
        this.nomps = nomps;
    }
    public String getDescriptionps() {
        return this.descriptionps;
    }
    
    public void setDescriptionps(String descriptionps) {
        this.descriptionps = descriptionps;
    }
    public Integer getNbsemaines() {
        return this.nbsemaines;
    }
    
    public void setNbsemaines(Integer nbsemaines) {
        this.nbsemaines = nbsemaines;
    }
    public Set getContenirsses() {
        return this.contenirsses;
    }
    
    public void setContenirsses(Set contenirsses) {
        this.contenirsses = contenirsses;
    }
    public Set getProfils() {
        return this.profils;
    }
    
    public void setProfils(Set profils) {
        this.profils = profils;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.codeps);
        hash = 59 * hash + Objects.hashCode(this.nomps);
        hash = 59 * hash + Objects.hashCode(this.descriptionps);
        hash = 59 * hash + Objects.hashCode(this.nbsemaines);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Programmestandard other = (Programmestandard) obj;
        if (!Objects.equals(this.nomps, other.nomps)) {
            return false;
        }
        if (!Objects.equals(this.descriptionps, other.descriptionps)) {
            return false;
        }
        if (!Objects.equals(this.codeps, other.codeps)) {
            return false;
        }
        if (!Objects.equals(this.nbsemaines, other.nbsemaines)) {
            return false;
        }
        return true;
    }




}


