package metier;
// Generated 27 mars 2019 12:04:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Seancestandard generated by hbm2java
 */
public class Seancestandard  implements java.io.Serializable {


     private Integer codess;
     private String nomss;
     private String avisss;
     private Boolean bilanss;
     private Set contenireses = new HashSet(0);
     private Set contenirsses = new HashSet(0);

    public Seancestandard() {
    }

    public Seancestandard(String nomss, String avisss, Boolean bilanss, Set contenireses, Set contenirsses) {
       this.nomss = nomss;
       this.avisss = avisss;
       this.bilanss = bilanss;
       this.contenireses = contenireses;
       this.contenirsses = contenirsses;
    }
   
    public Integer getCodess() {
        return this.codess;
    }
    
    public void setCodess(Integer codess) {
        this.codess = codess;
    }
    public String getNomss() {
        return this.nomss;
    }
    
    public void setNomss(String nomss) {
        this.nomss = nomss;
    }
    public String getAvisss() {
        return this.avisss;
    }
    
    public void setAvisss(String avisss) {
        this.avisss = avisss;
    }
    public Boolean getBilanss() {
        return this.bilanss;
    }
    
    public void setBilanss(Boolean bilanss) {
        this.bilanss = bilanss;
    }
    public Set getContenireses() {
        return this.contenireses;
    }
    
    public void setContenireses(Set contenireses) {
        this.contenireses = contenireses;
    }
    public Set getContenirsses() {
        return this.contenirsses;
    }
    
    public void setContenirsses(Set contenirsses) {
        this.contenirsses = contenirsses;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 19 * hash + Objects.hashCode(this.codess);
        hash = 19 * hash + Objects.hashCode(this.nomss);
        hash = 19 * hash + Objects.hashCode(this.avisss);
        hash = 19 * hash + Objects.hashCode(this.bilanss);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Seancestandard other = (Seancestandard) obj;
        if (!Objects.equals(this.nomss, other.nomss)) {
            return false;
        }
        if (!Objects.equals(this.avisss, other.avisss)) {
            return false;
        }
        if (!Objects.equals(this.codess, other.codess)) {
            return false;
        }
        if (!Objects.equals(this.bilanss, other.bilanss)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Seancestandard{" + "nomss=" + nomss + '}';
    }
    




}


