package metier;
// Generated 27 mars 2019 12:04:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Seanceperso generated by hbm2java
 */
public class Seanceperso  implements java.io.Serializable {


     private Integer codesp;
     private Programmeperso programmeperso;
     private String nomsp;
     private String avissp;
     private Boolean bilansp;
     private Integer semainesp;
     private Integer ordresp;
     private Integer fccalme;
     private Integer fcflexion;
     private Integer fcexe;
     private Double mbras;
     private Double mpoitrine;
     private Double mtaille;
     private Double mhanches;
     private Double mcuisses;
     private Set exercicepersos = new HashSet(0);

    public Seanceperso() {
    }

	
    public Seanceperso(Programmeperso programmeperso) {
        this.programmeperso = programmeperso;
    }
    public Seanceperso(Programmeperso programmeperso, String nomsp, String avissp, Boolean bilansp, Integer semainesp, Integer ordresp, Integer fccalme, Integer fcflexion, Integer fcexe, Double mbras, Double mpoitrine, Double mtaille, Double mhanches, Double mcuisses, Set exercicepersos) {
       this.programmeperso = programmeperso;
       this.nomsp = nomsp;
       this.avissp = avissp;
       this.bilansp = bilansp;
       this.semainesp = semainesp;
       this.ordresp = ordresp;
       this.fccalme = fccalme;
       this.fcflexion = fcflexion;
       this.fcexe = fcexe;
       this.mbras = mbras;
       this.mpoitrine = mpoitrine;
       this.mtaille = mtaille;
       this.mhanches = mhanches;
       this.mcuisses = mcuisses;
       this.exercicepersos = exercicepersos;
    }
   
    public Integer getCodesp() {
        return this.codesp;
    }
    
    public void setCodesp(Integer codesp) {
        this.codesp = codesp;
    }
    public Programmeperso getProgrammeperso() {
        return this.programmeperso;
    }
    
    public void setProgrammeperso(Programmeperso programmeperso) {
        this.programmeperso = programmeperso;
    }
    public String getNomsp() {
        return this.nomsp;
    }
    
    public void setNomsp(String nomsp) {
        this.nomsp = nomsp;
    }
    public String getAvissp() {
        return this.avissp;
    }
    
    public void setAvissp(String avissp) {
        this.avissp = avissp;
    }
    public Boolean getBilansp() {
        return this.bilansp;
    }
    
    public void setBilansp(Boolean bilansp) {
        this.bilansp = bilansp;
    }
    public Integer getSemainesp() {
        return this.semainesp;
    }
    
    public void setSemainesp(Integer semainesp) {
        this.semainesp = semainesp;
    }
    public Integer getOrdresp() {
        return this.ordresp;
    }
    
    public void setOrdresp(Integer ordresp) {
        this.ordresp = ordresp;
    }
    public Integer getFccalme() {
        return this.fccalme;
    }
    
    public void setFccalme(Integer fccalme) {
        this.fccalme = fccalme;
    }
    public Integer getFcflexion() {
        return this.fcflexion;
    }
    
    public void setFcflexion(Integer fcflexion) {
        this.fcflexion = fcflexion;
    }
    public Integer getFcexe() {
        return this.fcexe;
    }
    
    public void setFcexe(Integer fcexe) {
        this.fcexe = fcexe;
    }
    public Double getMbras() {
        return this.mbras;
    }
    
    public void setMbras(Double mbras) {
        this.mbras = mbras;
    }
    public Double getMpoitrine() {
        return this.mpoitrine;
    }
    
    public void setMpoitrine(Double mpoitrine) {
        this.mpoitrine = mpoitrine;
    }
    public Double getMtaille() {
        return this.mtaille;
    }
    
    public void setMtaille(Double mtaille) {
        this.mtaille = mtaille;
    }
    public Double getMhanches() {
        return this.mhanches;
    }
    
    public void setMhanches(Double mhanches) {
        this.mhanches = mhanches;
    }
    public Double getMcuisses() {
        return this.mcuisses;
    }
    
    public void setMcuisses(Double mcuisses) {
        this.mcuisses = mcuisses;
    }
    public Set getExercicepersos() {
        return this.exercicepersos;
    }
    
    public void setExercicepersos(Set exercicepersos) {
        this.exercicepersos = exercicepersos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.codesp);
        hash = 97 * hash + Objects.hashCode(this.nomsp);
        hash = 97 * hash + Objects.hashCode(this.avissp);
        hash = 97 * hash + Objects.hashCode(this.bilansp);
        hash = 97 * hash + Objects.hashCode(this.semainesp);
        hash = 97 * hash + Objects.hashCode(this.ordresp);
        hash = 97 * hash + Objects.hashCode(this.fccalme);
        hash = 97 * hash + Objects.hashCode(this.fcflexion);
        hash = 97 * hash + Objects.hashCode(this.fcexe);
        hash = 97 * hash + Objects.hashCode(this.mbras);
        hash = 97 * hash + Objects.hashCode(this.mpoitrine);
        hash = 97 * hash + Objects.hashCode(this.mtaille);
        hash = 97 * hash + Objects.hashCode(this.mhanches);
        hash = 97 * hash + Objects.hashCode(this.mcuisses);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Seanceperso other = (Seanceperso) obj;
        if (!Objects.equals(this.nomsp, other.nomsp)) {
            return false;
        }
        if (!Objects.equals(this.avissp, other.avissp)) {
            return false;
        }
        if (!Objects.equals(this.codesp, other.codesp)) {
            return false;
        }
        if (!Objects.equals(this.bilansp, other.bilansp)) {
            return false;
        }
        if (!Objects.equals(this.semainesp, other.semainesp)) {
            return false;
        }
        if (!Objects.equals(this.ordresp, other.ordresp)) {
            return false;
        }
        if (!Objects.equals(this.fccalme, other.fccalme)) {
            return false;
        }
        if (!Objects.equals(this.fcflexion, other.fcflexion)) {
            return false;
        }
        if (!Objects.equals(this.fcexe, other.fcexe)) {
            return false;
        }
        if (!Objects.equals(this.mbras, other.mbras)) {
            return false;
        }
        if (!Objects.equals(this.mpoitrine, other.mpoitrine)) {
            return false;
        }
        if (!Objects.equals(this.mtaille, other.mtaille)) {
            return false;
        }
        if (!Objects.equals(this.mhanches, other.mhanches)) {
            return false;
        }
        if (!Objects.equals(this.mcuisses, other.mcuisses)) {
            return false;
        }
        return true;
    }




}


