package metier;
// Generated 27 mars 2019 10:56:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Semainess generated by hbm2java
 */
public class Semainess  implements java.io.Serializable {


     private int semainess;
     private Set contenirsses = new HashSet(0);

    public Semainess() {
    }

	
    public Semainess(int semainess) {
        this.semainess = semainess;
    }
    public Semainess(int semainess, Set contenirsses) {
       this.semainess = semainess;
       this.contenirsses = contenirsses;
    }
   
    public int getSemainess() {
        return this.semainess;
    }
    
    public void setSemainess(int semainess) {
        this.semainess = semainess;
    }
    public Set getContenirsses() {
        return this.contenirsses;
    }
    
    public void setContenirsses(Set contenirsses) {
        this.contenirsses = contenirsses;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + this.semainess;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Semainess other = (Semainess) obj;
        if (this.semainess != other.semainess) {
            return false;
        }
        return true;
    }




}


