package metier;
// Generated 27 mars 2019 12:04:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Typeabonnement generated by hbm2java
 */
public class Typeabonnement  implements java.io.Serializable {


     private Integer codeta;
     private String libelleta;
     private Set clients = new HashSet(0);

    public Typeabonnement() {
    }

    public Typeabonnement(String libelleta, Set clients) {
       this.libelleta = libelleta;
       this.clients = clients;
    }
   
    public Integer getCodeta() {
        return this.codeta;
    }
    
    public void setCodeta(Integer codeta) {
        this.codeta = codeta;
    }
    public String getLibelleta() {
        return this.libelleta;
    }
    
    public void setLibelleta(String libelleta) {
        this.libelleta = libelleta;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.codeta);
        hash = 79 * hash + Objects.hashCode(this.libelleta);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Typeabonnement other = (Typeabonnement) obj;
        if (!Objects.equals(this.libelleta, other.libelleta)) {
            return false;
        }
        if (!Objects.equals(this.codeta, other.codeta)) {
            return false;
        }
        return true;
    }




}


